name: Add Credentials
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username for RabbitMQ'
        required: true
      password:
        description: 'Password for RabbitMQ'
        required: true

jobs:
  add_creds:
    runs-on:
      group: EC2
      labels: [self-hosted, deploy]
    steps:
      - name: Register User in RabbitMQ
        run: |
          docker exec -it ${{ secrets.SERVICE_NAME }} rabbitmqctl add_user ${{ github.event.inputs.username }} ${{ github.event.inputs.password }}
          docker exec -it ${{ secrets.SERVICE_NAME }} rabbitmqctl set_user_tags ${{ github.event.inputs.username }} administrator
          docker exec -it ${{ secrets.SERVICE_NAME }} rabbitmqctl set_permissions_globally ${{ github.event.inputs.username }} ".*" ".*" ".*"
          docker exec -it ${{secrets.SERVICE_NAME }} rabbitmqctl list_users
