name: Add Credentials
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username for RabbitMQ'
        required: true
      password:
        description: 'Password for RabbitMQ'
        required: true

jobs:
  add_creds:
    runs-on:
      group: EC2
      labels: [self-hosted, deploy]
    steps:
      - name: Get container id
        id: get_container_id
        run: |
          CONTAINER_ID=$(docker ps -q --filter "name=${{ secrets.SERVICE_NAME }}")
          echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV

      - name: Register User in RabbitMQ
        run: |
          docker exec -it ${{ env.CONTAINER_ID }} rabbitmqctl add_user ${{ github.event.inputs.username }} ${{ github.event.inputs.password }}
          docker exec -it ${{ env.CONTAINER_ID }} rabbitmqctl set_user_tags ${{ github.event.inputs.username }} administrator
          docker exec -it ${{ env.CONTAINER_ID }} rabbitmqctl set_permissions_globally ${{ github.event.inputs.username }} ".*" ".*" ".*"
          docker exec -it ${{ env.CONTAINER_ID }} rabbitmqctl list_users
