name: Push-to-EC2
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SWECC_RABBIT_TOKEN }}

      - name: Build and push
        run: |
          docker pull rabbitmq:3-management
          docker tag rabbitmq:3-management ${{ secrets.DOCKERHUB_USERNAME }}/swecc-rabbit:latest 
          docker tag rabbitmq:3-management ${{ secrets.DOCKERHUB_USERNAME }}/swecc-rabbit:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/swecc-rabbit:latest 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/swecc-rabbit:${{ github.sha }}

  deploy_to_swarm:
    needs: push_to_dockerhub
    runs-on:
      group: EC2
      labels: [self-hosted, deploy]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          docker service rm ${{ secrets.SERVICE_NAME }} | true

          docker service create \
            --name ${{ secrets.SERVICE_NAME }} \
            --network prod_swecc-network \
            --mount type=volume,src=rabbitmq_data,dst=/var/lib/rabbitmq\
            --replicas 1 \
            --restart-condition any\
            -p 5672:5672\
            ${{ secrets.DOCKERHUB_USERNAME }}/swecc-rabbit:latest
