name: Push-to-EC2
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on:
      group: EC2
      labels: [self-hosted, deploy]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SWECC_RABBIT_TOKEN }}

      - name: Build and push
        run: |
          docker pull rabbitmq:3-management
          docker tag rabbitmq:3-management ${{ secrets.DOCKERHUB_USERNAME }}/rabbitmq:latest 
          docker tag rabbitmq:3-management ${{ secrets.DOCKERHUB_USERNAME }}/rabbitmq:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rabbitmq:latest 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rabbitmq:${{ github.sha }}

      - name: Deploy
        run: |
          docker stop swecc-rabbit-instance || true
          docker rm swecc-rabbit-instance || true

          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/swecc-rabbitmq:latest

          docker run -d \
            --name swecc-rabbit-instance \
            --network swag-network \
            -p 5672:5672 \
            -p 15672:15672 \
            -v swecc-rabbit-data:/var/lib/rabbitmq \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/swecc-rabbitmq:latest
